=== haokiet/xml_QLBD/XML/XML/DataSource/QLBD.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="QLBD">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="TINH" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="MATINH">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="10"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="TENTINH">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="50"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="SANVD" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="MASAN">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="10"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="TENSAN">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="50"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="DIACHI">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="100"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="QUOCGIA" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="MAQG">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="10"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="TENQG">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="50"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="CAULACBO" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="MACLB">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="10"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="TENCLB">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="50"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="MASAN">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="10"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="MATINH">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="10"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="CAUTHU" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="MACT">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="10"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="HOTEN">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="50"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="VITRI">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="50"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="NGAYSINH" type="xs:date"/>
                            <xs:element name="DIACHI">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="100"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="MACLB">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="10"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="MAQG">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="10"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="SO" type="xs:int"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="HLV" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="MAHLV">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="10"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="TENHLV">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="50"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="NGAYSINH" type="xs:date"/>
                            <xs:element name="DIACHI">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="100"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="DIENTHOAI">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="11"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="MAQG">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="10"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="HLV_CLB" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="MAHLV">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="10"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="MACLB">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="10"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="VAITRO">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="50"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="TRANDAU" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="MATRAN">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="10"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="NAM">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="10"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="NGAYTD" type="xs:date"/>
                            <xs:element name="VONG" type="xs:int"/>
                            <xs:element name="MACLB1">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="10"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="MACLB2">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="10"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="MASAN">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="10"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="KETQUA">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="50"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="BANGXH" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="MACLB">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="10"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="NAM">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="10"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="VONG" type="xs:int"/>
                            <xs:element name="SOTRAN" type="xs:int"/>
                            <xs:element name="THANG" type="xs:int"/>
                            <xs:element name="HOA" type="xs:int"/>
                            <xs:element name="THUA" type="xs:int"/>
                            <xs:element name="DIEM" type="xs:int"/>
                            <xs:element name="HIEUSO">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="50"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="HANG" type="xs:int"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
        <xs:key name="CAUTHU_KEY">
            <xs:selector xpath="CAUTHU"/>
            <xs:field xpath="MACT"/>
        </xs:key>
        <xs:key name="QUOCGIA_KEY">
            <xs:selector xpath="QUOCGIA"/>
            <xs:field xpath="MAQG"/>
        </xs:key>
        <xs:key name="CAULACBO_KEY">
            <xs:selector xpath="CAULACBO"/>
            <xs:field xpath="MACLB"/>
        </xs:key>
        <xs:key name="TINH_KEY">
            <xs:selector xpath="TINH"/>
            <xs:field xpath="MATINH"/>
        </xs:key>
        <xs:key name="SANVD_KEY">
            <xs:selector xpath="SANVD"/>
            <xs:field xpath="MASAN"/>
        </xs:key>
        <xs:key name="HUANLUYENVIEN_KEY">
            <xs:selector xpath="HLV"/>
            <xs:field xpath="MAHLV"/>
        </xs:key>
        <xs:key name="HLV_CLB_KEY">
            <xs:selector xpath="HLV_CLB"/>
            <xs:field xpath="MAHLV"/>
        </xs:key>
        <xs:key name="TRANDAU_KEY">
            <xs:selector xpath="TRANDAU"/>
            <xs:field xpath="MATRAN"/>
        </xs:key>
        <xs:key name="BANGXH_KEY">
            <xs:selector xpath="BANGXH"/>
            <xs:field xpath="MACLB"/>
            <xs:field xpath="NAM"/>
            <xs:field xpath="VONG"/>
        </xs:key>
        <xs:keyref name="CAUTHU_REF1" refer="CAULACBO_KEY">
            <xs:selector xpath="CAULACBO"/>
            <xs:field xpath="MACLB"/>
        </xs:keyref>
        <xs:keyref name="CAUTHU_REF2" refer="QUOCGIA_KEY">
            <xs:selector xpath="QUOCGIA"/>
            <xs:field xpath="MAQG"/>
        </xs:keyref>
        <xs:keyref name="CAULACBO_REF" refer="SANVD_KEY">
            <xs:selector xpath="SANVD"/>
            <xs:field xpath="MASAN"/>
        </xs:keyref>
        <xs:keyref name="CAULACBO_REF2" refer="TINH_KEY">
            <xs:selector xpath="TINH"/>
            <xs:field xpath="MATINH"/>
        </xs:keyref>
        <xs:keyref name="HUANLUYENVIEN_REF" refer="QUOCGIA_KEY">
            <xs:selector xpath="QUOCGIA"/>
            <xs:field xpath="MAQG"/>
        </xs:keyref>
        <xs:keyref name="HLV_CLB_REF1" refer="HUANLUYENVIEN_KEY">
            <xs:selector xpath="HLV"/>
            <xs:field xpath="MAHLV"/>
        </xs:keyref>
        <xs:keyref name="HLV_CLB_REF2" refer="CAULACBO_KEY">
            <xs:selector xpath="CAULACBO"/>
            <xs:field xpath="MACLB"/>
        </xs:keyref>
        <xs:keyref name="TRANDAU_REF" refer="SANVD_KEY">
            <xs:selector xpath="SANVD"/>
            <xs:field xpath="MASAN"/>
        </xs:keyref>
        <xs:keyref name="BANGXH_REF" refer="CAULACBO_KEY">
            <xs:selector xpath="CAULACBO"/>
            <xs:field xpath="MACLB"/>
        </xs:keyref>
        <xs:unique name="TenSanUnique">
            <xs:selector xpath="SANVD"/>
            <xs:field xpath="TENSAN"/>
        </xs:unique>
        <xs:keyref name="TRANDAU_REF2" refer="CAULACBO_KEY">
            <xs:selector xpath="CAULACBO"/>
            <xs:field xpath="MACLB"/>
        </xs:keyref>
    </xs:element>
</xs:schema>

=== haokiet/xml_QLBD/XML/XML/DataSource/XMLFile1.xml
<?xml version="1.0" encoding="utf-8"?>
<QLBD xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="QLBD.xsd">
  <TINH>
    <MATINH>T1</MATINH>
    <TENTINH>Tinh 1</TENTINH>
  </TINH>
  <SANVD>
    <MASAN>San01</MASAN>
    <TENSAN>Hoàng Anh</TENSAN>
    <DIACHI>S1</DIACHI>
  </SANVD>
  <QUOCGIA>
    <MAQG>QG1</MAQG>
    <TENQG>Viet Na</TENQG>
  </QUOCGIA>
  <QUOCGIA>
    <MAQG>QG2</MAQG>
    <TENQG>Trung quoc</TENQG>
  </QUOCGIA>
  <CAULACBO>
    <MACLB>CLB1</MACLB>
    <TENCLB>cau lac bo 1</TENCLB>
    <MASAN>S1</MASAN>
    <MATINH>T1</MATINH>
  </CAULACBO>
  <CAULACBO>
    <MACLB>CLB2</MACLB>
    <TENCLB>cau lac bo 2</TENCLB>
    <MASAN>S1</MASAN>
    <MATINH>T1</MATINH>
  </CAULACBO>
  <CAUTHU>
    <MACT>CT1</MACT>
    <HOTEN>Nguyen tien linh</HOTEN>
    <VITRI>Tien dao</VITRI>
    <NGAYSINH>2000-11-01</NGAYSINH>
    <DIACHI>Nha TRang</DIACHI>
    <MACLB>CLB1</MACLB>
    <MAQG>QG1</MAQG>
    <SO>01</SO>
  </CAUTHU>
  <CAUTHU>
    <MACT>CT4</MACT>
    <HOTEN>Tien dao</HOTEN>
    <VITRI>Nguyen tien linh</VITRI>
    <NGAYSINH>2001-02-11</NGAYSINH>
    <DIACHI>Nha TRang</DIACHI>
    <MACLB>CLB1</MACLB>
    <MAQG>QG2</MAQG>
    <SO>02</SO>
  </CAUTHU>
  <HLV>
    <MAHLV>HLV14</MAHLV>
    <TENHLV>nguyen ngoc y</TENHLV>
    <NGAYSINH>2001-07-11</NGAYSINH>
    <DIACHI>nha</DIACHI>
    <DIENTHOAI>alo</DIENTHOAI>
    <MAQG>QG1</MAQG>
  </HLV>
  <HLV>
    <MAHLV>12</MAHLV>
    <TENHLV>t</TENHLV>
    <NGAYSINH>2001-08-12</NGAYSINH>
    <DIACHI>2</DIACHI>
    <DIENTHOAI>09090</DIENTHOAI>
    <MAQG>QG2</MAQG>
  </HLV>
  <HLV_CLB>
    <MAHLV>HLV1</MAHLV>
    <MACLB>CLB1</MACLB>
    <VAITRO>chiu</VAITRO>
  </HLV_CLB>
  <HLV_CLB>
    <MAHLV></MAHLV>
    <MACLB></MACLB>
    <VAITRO>KHONG KHI</VAITRO>
  </HLV_CLB>
  <TRANDAU>
    <MATRAN>m1</MATRAN>
    <NAM>2000</NAM>
    <NGAYTD>2000-11-02</NGAYTD>
    <VONG>1</VONG>
    <MACLB1>CLB1</MACLB1>
    <MACLB2>CLB1</MACLB2>
    <MASAN>S1</MASAN>
    <KETQUA>2 0</KETQUA>
  </TRANDAU>
  <BANGXH>
    <MACLB>CLB1</MACLB>
    <NAM>200</NAM>
    <VONG>1</VONG>
    <SOTRAN>1</SOTRAN>
    <THANG>1</THANG>
    <HOA>0</HOA>
    <THUA>0</THUA>
    <DIEM>1</DIEM>
    <HIEUSO>1</HIEUSO>
    <HANG>1</HANG>
  </BANGXH>
</QLBD>
